// プロトタイプ用サンプルデータ
// 本番では Spotify API / Discogs API / MusicBrainz から取得してDBに格納する。
// youtubeId は YouTube Data API の検索結果から埋める想定のため、ここでは null。
// stampSeed は「ネット上のレビューをLLMでムード分析した初期値」を模した仮の数値。

const STAMPS = [
  { id: 'doro',    label: 'ドロドロ',   en: 'murky',    color: '#7b5cff' },
  { id: 'horror',  label: 'ホラー',     en: 'horror',   color: '#c2372f' },
  { id: 'mellow',  label: 'メロウ',     en: 'mellow',   color: '#4aa3a0' },
  { id: 'smooth',  label: 'スムース',   en: 'smooth',   color: '#3f7fd6' },
  { id: 'aishu',   label: '哀愁',       en: 'melancholy', color: '#8a6fa8' },
  { id: 'bangin',  label: 'バンギン',   en: "bangin'",  color: '#d9822b' },
  { id: 'funky',   label: 'ファンキー', en: 'funky',    color: '#c9a227' },
  { id: 'laidbk',  label: 'レイドバック', en: 'laid-back', color: '#5f9e5f' },
  { id: 'dark',    label: 'ダーク',     en: 'dark',     color: '#5a5f70' },
  { id: 'party',   label: 'パーティー', en: 'party',    color: '#d4568c' },
];

// 地域(出身地)が特定できなかった収集物の置き場。
// 西海岸から少し離した太平洋上に浮かべ、「まだ漂着していない情報」として見せる。
// scripts/collect_grap.py が地域を解決できなかった候補はここに集約する想定。
const UNCLASSIFIED_REGION = {
  id: 'unclassified', name: '未確認情報', area: 'UNCHARTED — 出身地未特定',
  lng: -129, lat: 36,
  unclassified: true,
  albums: [],
};

const REGIONS = [
  UNCLASSIFIED_REGION,
  {
    id: 'compton', name: 'Compton', area: 'Los Angeles County, CA',
    lng: -118.2201, lat: 33.8958,
    albums: [
      { artist: 'N.W.A', title: 'Straight Outta Compton', year: 1988, label: 'Ruthless', youtubeId: null,
        stampSeed: { bangin: 96, dark: 61, doro: 34, funky: 52 } },
      { artist: 'DJ Quik', title: 'Quik Is the Name', year: 1991, label: 'Profile', youtubeId: null,
        stampSeed: { funky: 88, smooth: 71, party: 55, laidbk: 44 } },
      { artist: "Compton's Most Wanted", title: 'Music to Driveby', year: 1992, label: 'Orpheus', youtubeId: null,
        stampSeed: { doro: 74, aishu: 58, dark: 49, mellow: 31 } },
      { artist: 'MC Eiht', title: 'We Come Strapped', year: 1994, label: 'Epic Street', youtubeId: null,
        stampSeed: { doro: 41, dark: 33, bangin: 27 } },
      { artist: 'Eazy-E', title: 'Eazy-Duz-It', year: 1988, label: 'Ruthless', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3043455', stampSeed: { bangin: 68, funky: 45, dark: 40 } },
      { artist: 'Above The Law', title: "Livin' Like Hustlers", year: 1989, label: 'Ruthless/Epic', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/7217751', stampSeed: { funky: 57, bangin: 44, dark: 30 } },
      { artist: 'H.W.A.', title: "Livin' in a Hoe House", year: 1990, label: 'Drive-By', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3597493', stampSeed: { doro: 19, bangin: 15, dark: 11 } },
      { artist: "Compton's Most Wanted", title: "It's a Compton Thang", year: 1990, label: 'Orpheus Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4522759', stampSeed: { bangin: 33, dark: 25, doro: 20 } },
      { artist: 'CPO', title: 'To Hell and Black', year: 1990, label: 'Capitol', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/20932873', stampSeed: { dark: 28, bangin: 21, doro: 17 } },
      { artist: 'N.W.A', title: 'Efil4zaggin', year: 1991, label: 'Ruthless', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/9394940', stampSeed: { bangin: 71, dark: 54, doro: 38 } },
      { artist: 'AMG', title: 'Bitch Betta Have My Money', year: 1991, label: 'Select Street Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/13748375', stampSeed: { funky: 27, party: 20, bangin: 16 } },
      { artist: 'Dr. Dre', title: 'The Chronic', year: 1992, label: 'Interscope Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3108660', stampSeed: { funky: 97, bangin: 88, mellow: 62, dark: 55 } },
      { artist: 'DJ Quik', title: 'Way 2 Fonky', year: 1992, label: 'Profile Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4744151', stampSeed: { funky: 62, smooth: 48, party: 37 } },
      { artist: 'Above the Law', title: 'Black Mafia Life', year: 1992, label: 'Ruthless Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/29423104', stampSeed: { funky: 41, bangin: 33, dark: 24 } },
      { artist: 'Hi-C', title: 'Skanless', year: 1991, label: 'Skanless Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/13018967', stampSeed: { bangin: 22, funky: 17, dark: 13 } },
      { artist: 'Penthouse Players Clique', title: 'Paid the Cost', year: 1992, label: 'Ruthless Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/10402036', stampSeed: { funky: 20, bangin: 15, dark: 11 } },
      { artist: 'OFTB', title: 'Straight Up Watts', year: 1992, label: 'Big Beat', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/474030', stampSeed: { dark: 19, bangin: 15, doro: 11 } },
      { artist: 'Toddy Tee', title: 'Living on the Edge of Insanity (The Life Album)', year: 1992, label: 'Pump Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1833009', stampSeed: { funky: 16, bangin: 12, dark: 9 } },
      { artist: 'Mel-Low', title: 'Return of the Player', year: 1993, label: 'Rush Associated Labels', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/23848199', stampSeed: { funky: 18, bangin: 13, party: 10 } },
      { artist: 'Kam', title: 'Neva Again', year: 1993, label: 'EastWest', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/801308', stampSeed: { bangin: 26, dark: 20, doro: 15 } },
      { artist: 'DMG', title: 'Rigormortiz', year: 1993, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1148409', stampSeed: { dark: 22, doro: 17, bangin: 13 } },
      { artist: 'Rodney O & Joe Cooley', title: 'F**k New York', year: 1993, label: 'Psychotic Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/11413386', stampSeed: { bangin: 20, funky: 15, dark: 11 } },
      { artist: 'A.L.T.', title: 'Stone Cold World', year: 1993, label: 'Par Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1354525', stampSeed: { funky: 17, bangin: 12, party: 9 } },
      { artist: 'Yo-Yo', title: 'You Better Ask Somebody', year: 1993, label: 'EastWest Records America', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/36565867', stampSeed: { funky: 24, bangin: 17, party: 13 } },
      { artist: 'MC Ren', title: 'Shock of the Hour', year: 1993, label: 'Ruthless Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/16153297', stampSeed: { bangin: 40, dark: 32, doro: 23 } },
      { artist: 'Att Will', title: 'Do It Att Will', year: 1993, label: 'Big City Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/5358780', stampSeed: { bangin: 14, funky: 11, dark: 8 } },
      { artist: 'Arabian Prince', title: "Where's My Bytches", year: 1993, label: 'Da Bozak', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/5784861', stampSeed: { funky: 19, party: 14, bangin: 11 } },
    ],
  },
  {
    id: 'longbeach', name: 'Long Beach', area: 'Los Angeles County, CA',
    lng: -118.1937, lat: 33.7701,
    albums: [
      { artist: 'Snoop Doggy Dogg', title: 'Doggystyle', year: 1993, label: 'Death Row', youtubeId: null,
        stampSeed: { smooth: 99, funky: 84, laidbk: 77, party: 63 } },
      { artist: 'Warren G', title: 'Regulate...G Funk Era', year: 1994, label: 'Violator/RAL', youtubeId: null,
        stampSeed: { mellow: 91, smooth: 80, laidbk: 68, aishu: 40 } },
      { artist: 'Domino', title: 'Domino', year: 1993, label: 'Outburst', youtubeId: null,
        stampSeed: { smooth: 22, party: 18, funky: 15 } },
      { artist: 'Tairrie B.', title: 'The Power of a Woman', year: 1990, label: 'MCA', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/184856', stampSeed: { bangin: 20, funky: 14, dark: 10 } },
    ],
  },
  {
    id: 'southcentral', name: 'South Central LA', area: 'Los Angeles, CA',
    lng: -118.2917, lat: 33.9897,
    albums: [
      { artist: 'Ice-T', title: 'Rhyme Pays', year: 1987, label: 'Sire', youtubeId: null,
        stampSeed: { bangin: 44, funky: 30, dark: 22 } },
      { artist: 'South Central Cartel', title: "'N Gatz We Truss", year: 1994, label: 'G.W.K./RAL', youtubeId: null,
        stampSeed: { doro: 29, aishu: 24, dark: 19 } },
      { artist: 'Ice-T', title: 'Power', year: 1988, label: 'Sire', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/9510142', stampSeed: { bangin: 51, dark: 33, funky: 27 } },
      { artist: 'Ice-T', title: 'The Iceberg (Freedom of Speech... Just Watch What You Say)', year: 1989, label: 'Sire', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/460162', stampSeed: { dark: 55, bangin: 42, doro: 30 } },
      { artist: 'Everlast', title: 'Forever Everlasting', year: 1990, label: 'Warner Bros.', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/17766007', stampSeed: { bangin: 22, funky: 16, dark: 12 } },
      { artist: 'Low Profile', title: "We're in This Together", year: 1989, label: 'CBS Associated', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/99225', stampSeed: { funky: 24, dark: 16, bangin: 13 } },
      { artist: 'Ice Cube', title: "AmeriKKKa's Most Wanted", year: 1990, label: 'Priority', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/35861755', stampSeed: { bangin: 89, dark: 66, doro: 44, funky: 38 } },
      { artist: 'Ice-T', title: 'O.G. Original Gangster', year: 1991, label: 'Sire', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/216514', stampSeed: { bangin: 74, dark: 48, doro: 35 } },
      { artist: 'Ice Cube', title: 'Death Certificate', year: 1991, label: '4th & Broadway', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/836406', stampSeed: { bangin: 82, dark: 70, doro: 47 } },
      { artist: 'Cypress Hill', title: 'Cypress Hill', year: 1991, label: 'Columbia', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/6278083', stampSeed: { doro: 58, dark: 44, horror: 22 } },
      { artist: 'WC and the Maad Circle', title: "Ain't a Damn Thang Changed", year: 1991, label: 'Priority', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/343920', stampSeed: { funky: 32, bangin: 24, dark: 17 } },
      { artist: 'South Central Cartel', title: 'South Central Madness', year: 1991, label: 'Pump Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/601270', stampSeed: { dark: 27, doro: 22, bangin: 18 } },
      { artist: 'Crazy Toones', title: 'A Touch of Maadness', year: 1991, label: 'Not On Label', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/34335325', stampSeed: { funky: 14, bangin: 10, dark: 8 } },
      { artist: 'Ice Cube', title: 'The Predator', year: 1992, label: '4th & Broadway', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/633770', stampSeed: { bangin: 78, dark: 60, doro: 41, funky: 35 } },
      { artist: 'Da Lench Mob', title: 'Guerillas in tha Mist', year: 1992, label: 'EastWest Records America', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/361812', stampSeed: { bangin: 48, dark: 38, doro: 26 } },
      { artist: 'Ice-T', title: 'Home Invasion', year: 1993, label: 'Sire', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/29661217', stampSeed: { bangin: 43, dark: 34, doro: 24 } },
      { artist: 'Ice Cube', title: 'Lethal Injection', year: 1993, label: 'Priority Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/10681890', stampSeed: { bangin: 55, funky: 42, dark: 33 } },
      { artist: 'Bloods & Crips', title: 'Bangin\' on Wax', year: 1993, label: 'Dangerous Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/308831', stampSeed: { bangin: 45, dark: 36, doro: 25 } },
      { artist: 'Ice-T', title: 'Check This Out', year: 1993, label: 'International Broadcast Recordings', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/10489535', stampSeed: { bangin: 22, dark: 16, funky: 12 } },
    ],
  },
  {
    id: 'vallejo', name: 'Vallejo', area: 'Bay Area, CA',
    lng: -122.2566, lat: 38.1041,
    albums: [
      { artist: 'E-40', title: 'In a Major Way', year: 1995, label: 'Sick Wid It/Jive', youtubeId: null,
        stampSeed: { funky: 57, bangin: 43, party: 35 } },
      { artist: 'Mac Dre', title: 'Young Black Brotha', year: 1989, label: 'Strictly Business', youtubeId: null,
        stampSeed: { funky: 21, party: 17, laidbk: 12 } },
      { artist: 'E-40', title: 'Federal', year: 1992, label: "Sick Wid' It Records", youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/654929', stampSeed: { funky: 35, bangin: 24, party: 19 } },
      { artist: 'Mac Dre', title: "What's Really Going On?", year: 1992, label: 'Strictly Business Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/10152027', stampSeed: { funky: 24, party: 18, laidbk: 14 } },
      { artist: 'Funky Aztecs', title: 'Chicano Blues', year: 1992, label: 'TNT Recordings', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/16362855', stampSeed: { funky: 19, doro: 14, bangin: 11 } },
      { artist: 'The Click', title: 'Down & Dirty', year: 1993, label: "Sick Wid' It Records", youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/13405376', stampSeed: { funky: 26, party: 20, bangin: 14 } },
      { artist: 'D-Shot', title: 'The Shot Calla', year: 1993, label: "Sick Wid' It Records", youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/505236', stampSeed: { funky: 20, bangin: 15, doro: 11 } },
      { artist: 'Mac Mall', title: 'Illegal Business?', year: 1993, label: 'Young Black Brotha Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/29226472', stampSeed: { funky: 33, mellow: 24, bangin: 19 } },
      { artist: 'B-Legit', title: "Tryin' to Get a Buck", year: 1993, label: "Sick Wid' It Records", youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1758646', stampSeed: { funky: 25, bangin: 18, party: 14 } },
      { artist: 'Suga T', title: "It's All Good", year: 1993, label: "Sick Wid' It Records", youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3625582', stampSeed: { funky: 20, party: 16, laidbk: 12 } },
    ],
  },
  {
    id: 'oakland', name: 'Oakland', area: 'Bay Area, CA',
    lng: -122.2712, lat: 37.8044,
    albums: [
      { artist: 'Too $hort', title: 'Life Is...Too $hort', year: 1988, label: 'Dangerous Music/Jive', youtubeId: null,
        stampSeed: { funky: 48, laidbk: 39, party: 30 } },
      { artist: 'Spice 1', title: 'Spice 1', year: 1992, label: 'Jive', youtubeId: null,
        stampSeed: { doro: 33, dark: 26, bangin: 24 } },
      { artist: 'Too $hort', title: 'Born to Mack', year: 1987, label: 'Dangerous Music/Jive', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/319314', stampSeed: { funky: 29, laidbk: 22, party: 18 } },
      { artist: 'A.P.G. Crew', title: 'On the Rise', year: 1989, label: 'Metro', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1076546', stampSeed: { funky: 8, laidbk: 6, doro: 5 } },
      { artist: '415', title: '41Fivin', year: 1990, label: 'Big League', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4189785', stampSeed: { funky: 21, laidbk: 15, party: 12 } },
      { artist: 'Richie Rich', title: "Don't Do It", year: 1990, label: 'Big League', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3196664', stampSeed: { funky: 26, bangin: 18, party: 14 } },
      { artist: 'Too $hort', title: "Short Dog's in the House", year: 1990, label: 'Jive', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/16819746', stampSeed: { funky: 41, laidbk: 30, party: 24 } },
      { artist: '2Pac', title: '2Pacalypse Now', year: 1991, label: 'Interscope', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4354228', stampSeed: { doro: 51, aishu: 39, dark: 33, bangin: 28 } },
      { artist: '415', title: 'Nu Niggaz on tha Blokkk', year: 1991, label: 'Priority', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3573082', stampSeed: { funky: 19, bangin: 14, party: 11 } },
      { artist: 'A.P.G. Crew', title: "Oaktown's Finest", year: 1991, label: 'Yo! Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/336824', stampSeed: { funky: 9, laidbk: 7, doro: 5 } },
      { artist: 'Chunk', title: 'Menace to the Game', year: 1991, label: 'Tandem Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3063904', stampSeed: { bangin: 15, dark: 11, doro: 8 } },
      { artist: 'Dangerous Dame', title: 'I Got What You Want', year: 1990, label: 'Atlantic', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/15665840', stampSeed: { funky: 13, party: 10, laidbk: 8 } },
      { artist: 'Totally Insane', title: 'Direct from the Backstreet', year: 1991, label: 'RCA', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/12332239', stampSeed: { doro: 18, dark: 13, bangin: 10 } },
      { artist: 'Spice 1', title: 'Let It Be Known', year: 1991, label: 'Triad Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/2263925', stampSeed: { doro: 20, dark: 15, bangin: 12 } },
      { artist: 'Chunk', title: 'Chunk II: Still the Menace', year: 1992, label: 'Tandem Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/696084', stampSeed: { bangin: 17, dark: 12, doro: 9 } },
      { artist: 'Chunk', title: 'Marked for Death', year: 1992, label: 'Tandem Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/696102', stampSeed: { bangin: 16, dark: 11, doro: 9 } },
      { artist: 'Seagram', title: 'The Dark Roads', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/498343', stampSeed: { doro: 30, dark: 24, aishu: 18 } },
      { artist: 'E-A-Ski', title: '1 Step Ahead of Yall', year: 1992, label: 'No Limit Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1982925', stampSeed: { funky: 22, bangin: 16, party: 12 } },
      { artist: 'Murder One Gangster', title: 'Exposed to the Game', year: 1992, label: 'Murder One Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4315377', stampSeed: { dark: 18, bangin: 14, doro: 11 } },
      { artist: '2Pac', title: 'Troublesome', year: 1992, label: 'Interscope Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/21221989', stampSeed: { doro: 40, aishu: 31, dark: 26 } },
      { artist: '2Pac', title: 'Strictly 4 My N.I.G.G.A.Z.', year: 1993, label: 'Interscope Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3960276', stampSeed: { doro: 62, aishu: 47, dark: 39, bangin: 33 } },
      { artist: 'Too $hort', title: 'Get in Where You Fit In', year: 1993, label: 'Jive', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3400257', stampSeed: { funky: 37, laidbk: 27, party: 21 } },
      { artist: 'The Conscious Daughters', title: 'Ear to the Street', year: 1993, label: 'Priority Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/872303', stampSeed: { funky: 22, dark: 16, bangin: 13 } },
      { artist: 'Totally Insane', title: 'Goin Insane', year: 1993, label: 'In-A-Minute Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4869628', stampSeed: { doro: 20, dark: 15, bangin: 11 } },
      { artist: 'Pooh-Man', title: 'Judgement Day', year: 1993, label: 'Righteous Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1552759', stampSeed: { dark: 17, bangin: 13, doro: 10 } },
    ],
  },
  {
    id: 'houston', name: 'Houston', area: 'Texas',
    lng: -95.3698, lat: 29.7604,
    albums: [
      { artist: 'Geto Boys', title: "We Can't Be Stopped", year: 1991, label: 'Rap-A-Lot', youtubeId: null,
        stampSeed: { horror: 72, dark: 66, doro: 51, aishu: 33 } },
      { artist: 'DJ Screw', title: '3 \'N the Mornin\' (Part Two)', year: 1996, label: 'Bigtyme', youtubeId: null,
        stampSeed: { doro: 38, mellow: 29, laidbk: 26 } },
      { artist: 'Convicts', title: 'Convicts', year: 1991, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/12735777', stampSeed: { bangin: 24, dark: 19, doro: 15 } },
      { artist: 'Geto Boys', title: 'Making Trouble', year: 1991, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3897370', stampSeed: { bangin: 22, dark: 16, doro: 12 } },
      { artist: 'Willie D', title: "I'm Goin' Out Lika Soldier", year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/847702', stampSeed: { bangin: 34, dark: 26, doro: 19 } },
      { artist: 'Big Mello', title: 'Bone Hard Zaggin', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1156304', stampSeed: { funky: 23, bangin: 17, doro: 13 } },
      { artist: 'Geto Boys', title: 'Grip It! On That Other Level', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4174538', stampSeed: { horror: 44, dark: 38, doro: 27 } },
      { artist: 'Trinity Garden Cartel', title: 'The Ghetto My Hood', year: 1992, label: 'Cartel Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/5389812', stampSeed: { dark: 21, bangin: 16, doro: 12 } },
      { artist: 'Bushwick Bill', title: 'Little Big Man', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/12644309', stampSeed: { horror: 29, dark: 23, doro: 17 } },
      { artist: 'Raheem', title: 'The Invincible', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/8607968', stampSeed: { funky: 20, bangin: 15, dark: 11 } },
      { artist: 'Geto Boys', title: 'Till Death Do Us Part', year: 1993, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/14686570', stampSeed: { dark: 33, doro: 26, horror: 20 } },
      { artist: 'Sat N Smooth', title: 'The Awakening', year: 1993, label: 'Flashpoint International', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/439073', stampSeed: { dark: 17, doro: 13, bangin: 10 } },
      { artist: 'K•Rino', title: 'Stories from the Black Book', year: 1993, label: 'Electric City Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/496967', stampSeed: { dark: 20, doro: 15, bangin: 11 } },
      { artist: '5th Ward Boyz', title: 'Ghetto Dope', year: 1993, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/5301655', stampSeed: { doro: 24, dark: 19, horror: 13 } },
      { artist: 'Scarface', title: 'The World Is Yours', year: 1993, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/22474649', stampSeed: { dark: 45, doro: 36, aishu: 26 } },
      { artist: 'Ganksta N-I-P', title: 'Psychic Thoughts', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/501707', stampSeed: { horror: 42, dark: 33, doro: 24 } },
    ],
  },
  {
    id: 'portarthur', name: 'Port Arthur', area: 'Texas',
    lng: -93.9399, lat: 29.8850,
    albums: [
      { artist: 'UGK', title: 'Too Hard to Swallow', year: 1992, label: 'Jive', youtubeId: null,
        stampSeed: { doro: 26, funky: 19, aishu: 14 } },
    ],
  },
  {
    id: 'memphis', name: 'Memphis', area: 'Tennessee',
    lng: -90.0490, lat: 35.1495,
    albums: [
      { artist: 'Three 6 Mafia', title: 'Mystic Stylez', year: 1995, label: 'Prophet', youtubeId: null,
        stampSeed: { horror: 94, dark: 78, doro: 62 } },
      { artist: 'Tommy Wright III', title: 'On the Run', year: 1996, label: 'Street Smart', youtubeId: null,
        stampSeed: { horror: 11, doro: 9, dark: 7 } },
      { artist: 'Gangsta Pat', title: '#1 Suspect', year: 1991, label: 'On Top Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4749203', stampSeed: { dark: 24, bangin: 18, doro: 14 } },
      { artist: 'Radical T', title: 'Radical but Critical', year: 1991, label: 'On Top Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/2163476', stampSeed: { doro: 14, dark: 10, horror: 8 } },
      { artist: 'N.O.T.S.', title: 'True Blue', year: 1992, label: "Ain't Jokin Records", youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3826172', stampSeed: { dark: 13, doro: 10, bangin: 8 } },
      { artist: 'Tommy Wright III', title: 'Memphis Massacre', year: 1992, label: 'T.W. Productions', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3593532', stampSeed: { horror: 15, doro: 11, dark: 9 } },
      { artist: 'Al Kapone', title: 'Street Knowledge, Chapters 1-12', year: 1992, label: 'Outlaw Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4172157', stampSeed: { dark: 20, doro: 16, bangin: 12 } },
      { artist: 'DJ Paul', title: 'Vol.15 "For Them Niggaz W/ Anna"', year: 1993, label: 'Not On Label', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/9285471', stampSeed: { horror: 24, dark: 19, doro: 14 } },
    ],
  },
  {
    id: 'neworleans', name: 'New Orleans', area: 'Louisiana',
    lng: -90.0715, lat: 29.9511,
    albums: [
      { artist: 'UNLV', title: 'Uptown 4 Life', year: 1996, label: 'Cash Money', youtubeId: null,
        stampSeed: { bangin: 13, party: 10, doro: 8 } },
      { artist: 'Master P', title: 'Ice Cream Man', year: 1996, label: 'No Limit', youtubeId: null,
        stampSeed: { bangin: 31, doro: 22, dark: 18 } },
      { artist: 'Master P', title: 'Get Away Clean', year: 1991, label: 'No Limit Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/11852898', stampSeed: { funky: 20, bangin: 15, party: 12 } },
      { artist: 'Master P', title: "Mama's Bad Boy", year: 1992, label: 'No Limit Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4778613', stampSeed: { funky: 22, bangin: 16, party: 13 } },
      { artist: 'Ruthless Juveniles', title: "Hard as Tha' F**k", year: 1992, label: 'Mobo Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/12918757', stampSeed: { bangin: 19, dark: 14, doro: 10 } },
      { artist: 'DJ Jimi', title: "It's Jimi", year: 1992, label: 'Soulin\' Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1456067', stampSeed: { party: 24, funky: 18, bangin: 12 } },
      { artist: 'TRU', title: "Who's da Killer?", year: 1993, label: 'No Limit Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1864242', stampSeed: { bangin: 24, dark: 18, doro: 14 } },
    ],
  },
  {
    id: 'sf', name: 'San Francisco', area: 'Hunters Point / Fillmore, CA',
    lng: -122.4194, lat: 37.7749,
    albums: [
      { artist: 'RBL Posse', title: 'A Lesson to Be Learned', year: 1992, label: 'In-A-Minute', youtubeId: null,
        stampSeed: { doro: 16, bangin: 13, funky: 11 } },
      { artist: 'Dre Dog', title: 'The New Jim Jones', year: 1993, label: 'In-A-Minute', youtubeId: null,
        stampSeed: { horror: 14, doro: 12, dark: 9 } },
      { artist: 'JT the Bigga Figga', title: "Don't Stop 'Til We Major", year: 1992, label: 'Lil Daddy Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1831086', stampSeed: { funky: 21, bangin: 15, party: 12 } },
      { artist: 'JT the Bigga Figga', title: 'Playaz N the Game', year: 1993, label: 'Get Low Recordz', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3851547', stampSeed: { funky: 22, bangin: 16, party: 13 } },
      { artist: 'San Quinn', title: "Don't Cross Me", year: 1993, label: 'Buck Fifty Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1135700', stampSeed: { funky: 19, bangin: 14, party: 11 } },
    ],
  },
  {
    id: 'sacramento', name: 'Sacramento', area: 'California',
    lng: -121.4944, lat: 38.5816,
    albums: [
      { artist: 'Brotha Lynch Hung', title: 'Season of da Siccness', year: 1995, label: 'Black Market', youtubeId: null,
        stampSeed: { horror: 47, doro: 39, dark: 34 } },
      { artist: 'X-Raided', title: 'Psycho Active', year: 1992, label: 'Black Market', youtubeId: null,
        stampSeed: { horror: 12, dark: 10, doro: 8 } },
      { artist: 'C-Bo', title: 'Gas Chamber', year: 1993, label: 'AWOL Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/7713328', stampSeed: { dark: 24, doro: 19, bangin: 14 } },
    ],
  },
  {
    // DS455 / OZROSAURUS は Discogs監査で style に Gangsta タグが
    // 一切付いていないことを確認したため削除(2026-08-06)。
    // 「世界のG-RAP」の枠自体は残し、条件を満たす盤が見つかり次第補充する。
    id: 'yokohama', name: 'Yokohama', area: 'Japan — 世界のG-RAP',
    lng: 139.6380, lat: 35.4437,
    albums: [
    ],
  },
  {
    id: 'queens', name: 'Queensbridge', area: 'New York, NY',
    lng: -73.9430, lat: 40.7550,
    albums: [
      { artist: 'Mobb Deep', title: 'The Infamous', year: 1995, label: 'Loud', youtubeId: null,
        stampSeed: { dark: 88, doro: 69, aishu: 57, horror: 30 } },
      { artist: 'Kool G Rap & DJ Polo', title: 'Live and Let Die', year: 1992, label: 'Cold Chillin\'', youtubeId: null,
        stampSeed: { dark: 28, bangin: 23, doro: 17 } },
      { artist: 'Kool G Rap & DJ Polo', title: 'Road to the Riches', year: 1989, label: 'Cold Chillin\'', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1050334', stampSeed: { dark: 21, bangin: 17, doro: 13 } },
      { artist: 'Kool G Rap & DJ Polo', title: 'Wanted: Dead or Alive', year: 1990, label: 'Cold Chillin\'', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/11354462', stampSeed: { dark: 33, bangin: 26, doro: 19 } },
      { artist: 'Royal Flush', title: '976-DOPE', year: 1991, label: 'Yo! Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/7322714', stampSeed: { dark: 17, bangin: 13, doro: 10 } },
      { artist: 'BWP', title: 'The Bytches', year: 1991, label: 'No Face', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/527825', stampSeed: { bangin: 16, funky: 11, doro: 9 } },
    ],
  },
  {
    id: 'philly', name: 'Philadelphia', area: 'Pennsylvania',
    lng: -75.1635, lat: 39.9527,
    albums: [
      { artist: 'Schoolly D', title: 'Schoolly-D', year: 1985, label: 'Schoolly-D Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/248450', stampSeed: { doro: 34, dark: 27, bangin: 19 } },
      { artist: 'Schoolly D', title: 'Saturday Night! - The Album', year: 1986, label: 'Schoolly-D Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/319359', stampSeed: { bangin: 30, dark: 22, doro: 18 } },
      { artist: 'Schoolly D', title: 'Smoke Some Kill', year: 1988, label: 'Jive', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/12250631', stampSeed: { doro: 22, dark: 18, horror: 12 } },
      { artist: 'Schoolly D', title: 'Am I Black Enough for You?', year: 1989, label: 'Jive', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/815457', stampSeed: { dark: 25, bangin: 19, doro: 15 } },
      { artist: 'Cool C', title: 'Life in the Ghetto', year: 1990, label: 'Atlantic', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/572921', stampSeed: { funky: 22, bangin: 17, doro: 13 } },
      { artist: 'Schoolly D', title: 'How a Blackman Feels', year: 1991, label: 'Capitol Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/500911', stampSeed: { bangin: 20, dark: 15, doro: 12 } },
    ],
  },
  {
    id: 'bronx', name: 'The Bronx', area: 'New York, NY',
    lng: -73.9167, lat: 40.8448,
    albums: [
      { artist: 'Just-Ice', title: 'Back to the Old School', year: 1986, label: 'Fresh', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/56036', stampSeed: { bangin: 24, dark: 17, doro: 12 } },
      { artist: 'Just-Ice', title: 'Kool & Deadly (Justicizms)', year: 1987, label: 'Fresh', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/795640', stampSeed: { bangin: 18, dark: 13, funky: 10 } },
      { artist: 'Just-Ice', title: 'The Desolate One', year: 1989, label: 'Fresh', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1685185', stampSeed: { dark: 16, doro: 12, bangin: 9 } },
      { artist: 'Boogie Down Productions', title: 'Criminal Minded', year: 1987, label: 'B-Boy', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/11179166', stampSeed: { bangin: 47, dark: 38, doro: 25 } },
      { artist: 'Donald-D', title: 'Notorious', year: 1989, label: 'Rhyme Syndicate/Rick Rubin', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/247560', stampSeed: { bangin: 14, funky: 10, dark: 8 } },
      { artist: 'Tim Dog', title: 'Penicillin on Wax', year: 1991, label: 'Ruffhouse Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1126548', stampSeed: { bangin: 30, dark: 22, doro: 16 } },
      { artist: 'Just-Ice', title: 'Gun Talk', year: 1993, label: 'Savage Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/21918118', stampSeed: { bangin: 21, dark: 16, doro: 12 } },
    ],
  },
  {
    id: 'dallas', name: 'Dallas', area: 'Texas',
    lng: -96.7969, lat: 32.7763,
    albums: [
      { artist: 'The D.O.C.', title: 'No One Can Do It Better', year: 1989, label: 'Ruthless/Atlantic', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3729520', stampSeed: { bangin: 62, funky: 41, party: 28 } },
      { artist: 'Point Blank', title: 'Prone to Bad Dreams', year: 1992, label: 'Bigtyme Recordz', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/474019', stampSeed: { dark: 22, bangin: 17, doro: 13 } },
    ],
  },
  {
    id: 'seattle', name: 'Seattle', area: 'Washington',
    lng: -122.3301, lat: 47.6038,
    albums: [
      { artist: 'Sir Mix-A-Lot', title: 'Swass', year: 1988, label: 'Nastymix', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1453446', stampSeed: { funky: 44, party: 39, bangin: 26 } },
      { artist: 'Criminal Nation', title: 'Release the Pressure', year: 1990, label: 'Nastymix', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1060371', stampSeed: { bangin: 19, dark: 14, doro: 10 } },
      { artist: 'Sir Mix-A-Lot', title: 'Mack Daddy', year: 1992, label: 'American Recordings', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/7656885', stampSeed: { funky: 51, party: 44, bangin: 30 } },
      { artist: 'Criminal Nation', title: 'Trouble in the Hood', year: 1992, label: 'Nastymix Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1060375', stampSeed: { bangin: 21, dark: 16, doro: 11 } },
    ],
  },
  {
    id: 'atlanta', name: 'Atlanta', area: 'Georgia',
    lng: -84.3898, lat: 33.7545,
    albums: [
      { artist: 'Tony M.F. Rock', title: 'Let Me Take You to the Rock House', year: 1989, label: 'Luke Skyywalker', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/29833837', stampSeed: { funky: 12, party: 10, bangin: 7 } },
      { artist: 'Success-N-Effect', title: 'Drive By of Uh Revolutionist', year: 1992, label: 'Umoja', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1202607', stampSeed: { dark: 16, bangin: 12, doro: 9 } },
      { artist: '1-5ive Posse', title: 'Lifestyles of the Young & Crazy', year: 1992, label: 'World Export Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/6718927', stampSeed: { funky: 11, party: 9, bangin: 7 } },
    ],
  },
  {
    id: 'sanantonio', name: 'San Antonio', area: 'Texas',
    lng: -98.4951, lat: 29.4246,
    albums: [
      { artist: 'Choice', title: 'The Big Payback', year: 1990, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/13031925', stampSeed: { bangin: 16, dark: 11, doro: 8 } },
      { artist: 'P.K.O.', title: 'Armed & Dangerous', year: 1990, label: 'Youngsta Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3851942', stampSeed: { bangin: 12, dark: 9, doro: 7 } },
      { artist: 'P.K.O.', title: "They Scared of a Nigga", year: 1992, label: 'Youngsta Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/697065', stampSeed: { bangin: 14, dark: 10, doro: 8 } },
      { artist: 'Choice', title: 'Stick-N-Moove', year: 1992, label: 'Rap-A-Lot Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/26709599', stampSeed: { bangin: 15, dark: 10, doro: 8 } },
    ],
  },
  {
    id: 'detroit', name: 'Detroit', area: 'Michigan',
    lng: -83.0458, lat: 42.3314,
    albums: [
      { artist: 'Esham', title: 'Boomin\' Words from Hell', year: 1989, label: 'Reel Life Productions', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/789568', stampSeed: { horror: 41, doro: 33, dark: 28 } },
      { artist: 'Natas', title: 'Life After Death', year: 1992, label: 'Reel Life Productions', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/4575540', stampSeed: { horror: 33, dark: 27, doro: 21 } },
      { artist: 'Bo$$', title: 'Born Gangstaz', year: 1993, label: 'DJ West', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/1162383', stampSeed: { bangin: 30, dark: 23, doro: 17 } },
      { artist: 'Menace to Society', title: 'Life of a Real One', year: 1993, label: 'CUSH Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/2175784', stampSeed: { dark: 19, bangin: 14, doro: 11 } },
    ],
  },
  {
    id: 'flint', name: 'Flint', area: 'Michigan',
    lng: -83.6875, lat: 43.0125,
    albums: [
      { artist: 'MC Breed', title: '20 Below', year: 1992, label: 'Ichiban Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/3778048', stampSeed: { funky: 26, bangin: 18, party: 14 } },
      { artist: 'Top Authority', title: "Somethin' to Blaze To", year: 1993, label: 'Trak Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/5184448', stampSeed: { funky: 17, bangin: 12, party: 10 } },
    ],
  },
  {
    // 「世界のG-RAP」— Discogs Gangstaタグ確認済みの海外作品
    id: 'saopaulo', name: 'São Paulo', area: 'Brazil — 世界のG-RAP',
    lng: -46.6334, lat: -23.5507,
    albums: [
      { artist: "Racionais MC's", title: 'Holocausto Urbano', year: 1990, label: 'Zambia', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/2748182', stampSeed: { dark: 37, doro: 29, bangin: 22 } },
      { artist: "Racionais MC's", title: 'Raio X Brasil - Liberdade de Expressão', year: 1993, label: 'Zimbabwe Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/170454', stampSeed: { dark: 42, doro: 33, aishu: 24 } },
    ],
  },
  {
    id: 'manila', name: 'Manila', area: 'Philippines — 世界のG-RAP',
    lng: 120.9804, lat: 14.5904,
    albums: [
      { artist: 'Francis M.', title: 'Yo!', year: 1990, label: 'OctoArts International', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/9153877', stampSeed: { funky: 18, party: 14, bangin: 10 } },
    ],
  },
  {
    id: 'carson', name: 'Carson', area: 'Los Angeles County, CA',
    lng: -118.2817, lat: 33.8317,
    albums: [
      { artist: 'Boo-Yaa T.R.I.B.E.', title: 'New Funky Nation', year: 1990, label: '4th & Broadway', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/712190', stampSeed: { bangin: 30, dark: 22, doro: 16 } },
    ],
  },
  {
    // 「世界のG-RAP」— Discogsで確認済みのオランダ発Gangsta作品
    id: 'amsterdam', name: 'Amsterdam', area: 'Netherlands — 世界のG-RAP',
    lng: 4.8952, lat: 52.3702,
    albums: [
      { artist: 'Osdorp Posse', title: 'Osdorp Stijl', year: 1992, label: 'Djax Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/2995060', stampSeed: { bangin: 20, dark: 15, doro: 11 } },
    ],
  },
  {
    id: 'miami', name: 'Miami', area: 'Florida',
    lng: -80.1918, lat: 25.7617,
    albums: [
      { artist: 'Poison Clan', title: 'Poisonous Mentality', year: 1992, label: 'Effect Records', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/552995', stampSeed: { bangin: 24, funky: 18, party: 14 } },
    ],
  },
  {
    id: 'eastorange', name: 'East Orange', area: 'New Jersey',
    lng: -74.2107, lat: 40.7673,
    albums: [
      { artist: 'Naughty By Nature', title: '19 Naughty III', year: 1993, label: 'Tommy Boy', youtubeId: null,
        discogsUrl: 'https://www.discogs.com/release/241357', stampSeed: { bangin: 36, party: 28, funky: 22 } },
    ],
  },
];
