// 自動生成: scripts/youtube_enrich.py (YouTube Data API v3)
// iTunesに無い盤の代替再生用。1日の検索クォータ制限があるため少しずつ埋まる。
const YOUTUBE = {
 "Menace|Confessing Sins": "ltA3Kevx7zg",
 "SandSpiders|Live II Tell": "pV06Na3_NMc",
 "Toot|Change Da Game": "Tuk9XUeEStw",
 "Tray Duece|Bayou Soldiers": "voWRWnV00Xg",
 "Big Blitz|All At Once": "jmx8iFiKppw",
 "D Jack|Sex Money & Murder": "fZzGtb1qjxk",
 "Fear|Lawless Entertainment": "Riflqfr0PpI",
 "China|The Game Way": "ploPmC0njPc",
 "B.I.G. AL|Strugglin' for a Mill...": "Q4SppzDISnQ",
 "Heavyweight|I'm Gonna Tell Ya Like It Is": "2SYDthj3Vaw",
 "CEA|A Shot In The Dark": "iSLqO4ZXA44",
 "Mike V.|Gameface Vision": "rhf7kO0V6aQ",
 "Buzz|In The Hands Of God": "nKndU7Djg04",
 "L Dog|The Sad Truth": "xco4cZL1_1Y",
 "F.U.|The Compulation": "rzEVTCEHtfs",
 "BAM|A Rough Nigga'z Bible Vol. II Hell On Earth": "WmHZ6wtbZyk",
 "T-Boy|City Of Lights": "wN9mcQzFejQ",
 "Cornbread|The Unseen": "jyS6wTo_Y-0",
 "The Professionals|Power Moves": "h4UDFI00hIM",
 "Canis|My Life In Exchange 4 Yours": "O2PUTUsETLA",
 "Gemini|Life In BC": "iNwC0sp-uA4",
 "CCA|For Tha Streetz Vol. 2": "RhX0GxaGQeY",
 "VIP|G.I. Style": "XNobxO-6gqM",
 "E.M.C.|I Got Dat Fire": "PKtDzSRTTdA",
 "Red|Addicted To Gettin' Paper": "cvdC_7g0JVA",
 "Big T|To All My Niggaz": "oF5QxIXnznc",
 "Facedown|Major Dealin'": "q1oa07Kw_RQ",
 "DJ World|Player's Life": "MWMOsaIgOiU",
 "Y.G.|Introducing": "_K2JdmUc8BY",
 "Mr. Ku|The World Is Near Dead": "cuuquJp_GMc",
 "Carlito's Way|Power Moves": "RTGqL7PnAg8",
 "Mr. Lawrence|How I'm Livin": "zgxNAemTh0Y",
 "Felony|Hit'em Get'em": "f4EEzmi5Ti4",
 "B.I.|4 Da Life Of Me": "PAjNIQKpDI4",
 "The Council|Relentless Screwed & Chopped": "7O8Ht7ZVIUc",
 "Ghost 13|Planet 13": "Rlw1fgpZBYM",
 "Pistol|Speedballn'": "qsYmjv04hxw",
 "Espionage|7002- A Tale Of Two Cities": "gpiPMS8LMN8",
 "KC|Vol 1: What Makes Me...": "TLiGxss8W_Q",
 "Sandman|No Secrets, No Lies": "F3_ZeWoL5iw",
 "The Cast|Show Me The Money": "UQiJTWpijjU",
 "F.O.D.|Mind Yo Business": "I7vuQCSn-uM",
 "Baby J|What R U Choosin Money Or Losin": "t3ZCoXcdnp8",
 "KLS|What I.B. Feelin'": "nXWL-KmMtHY",
 "Severe|Gritty": "TUTZWjlE1wU",
 "Lil' Boo|Do Not Cross": "0NHrijMoorA",
 "Duce|Chi-Town A Side": "Q8KiO4IFWVs",
 "Darkside|Nothin' To Lose": "3YGTILW6Fac",
 "Filthy|Til I Get There": "hsTjOHkgZQI",
 "Royalty|Helatite": "VXQZFX5Nm7A",
 "Anonymous|A2K - The Night The World Stood Still": "GktCdSWrFoo",
 "Ransom|Rehabilitation": "Ks2OWBR_pO8",
 "The Lunatics|Get That Money Shawty": "RtSDWq6HsJE",
 "C-No|We In The Middle": "X9wQJGaW9To",
 "Lost Soul|Miss Understood": "57CMh7a2tls",
 "SDA|The Return Of SDA": "CiH0s4E8994",
 "Maniac|Criminal Ties": "wK3bHll0ut4",
 "Architect|Rugged Desigins": "0EJdJAqW-1g",
 "Lil' Walt|The Ultimate Hustle": "qChpIqThsNM",
 "Hit Squad|The World Is \"R\"s": "VlImlygG7oA",
 "AR-15|Off Thee Hinges: Series 2000": "qAeogfvDt1c",
 "M.A.N.S.O.N.|La Familia": "JI6j2kzXY14",
 "360 Degrees|Grass Root Soldiers": "zWH-DG6qeDE",
 "Tank|Scarred 4 Life": "HGH4szqcL2Q",
 "Major League|It's Goin' Down": "zHfIVJV9T0w",
 "Kindred|Black Market": "ydVtKsBWo-A",
 "Chill|Where Ya From": "maW3K180y3c",
 "Lo-Down|Sex, Drugs, Rap": "amh8Fw8SxQA",
 "D.W.I.|Unda Tha Influenz": "UkNJ_IfXpGk",
 "Dreamer|Only If You Knew": "LCCiwPEdEpg",
 "RO|Everybody Come On": "uc6f_2nPSX8",
 "Mone|Ballaz Dreams": "M3rD3-ajwjM",
 "Body|Entrappment": "n9le_pu6SFw",
 "Stick|The Man And His Music": "Sw9L3SusV3Q",
 "D-Lo|Reality": "DzzKWpf2ObY",
 "Cut Throat|The Beginning": "4T0SXYbCFG4",
 "Hectic|The Introduction": "AzK5_OMxXFw",
 "L Dog|Da Sad Truth": "D32iuIhtIM0",
 "Strech|My Time": "kIG9Tt66TXE",
 "Untouchables|De' Mercinaries Vol !": "dgZxdT0Sgas",
 "Foul Play|Black Market": "4c5pOqfRwMc",
 "K.O.|Same As I Ever Was": "j0lzqvC0igg",
 "The Lunatics|www.wegonecrazy.com": "Q1qlroPxFbE",
 "Dead End|The Résumé - The Year 2000": "q6wL-519-6Q",
 "B-Low|Ski Mask Over My Evil Grin": "VMHA7BvCB6E",
 "Dirty Red|Inner Visions": "R4sWEqH1Hs8",
 "Mafia|Misery Loves Company": "bTHfivlSPpI",
 "Peeps|Which Wayz Up": "2IDua41JNGc",
 "Anonymous|Stone Cold Millennium Sh*t": "PbdP8rwb8hU",
 "Cherokee|The Promise": "3VcNNjFmU-E",
 "S.U.N.|Where Da Sun Don't Shine Vol. 1": "jql7ghuw7eQ",
 "London Boys|All My Life": "xtjeeHHkwC0",
 "Legend|Power To The People": "4Epue9X8bpc",
 "Fat Cat|The American Dream": "r9TRGWov8yM",
 "PMC|PMC 2000": "bvqroLOk0O8",
 "Shank|City Of Corruption": "CJeS2YR5lL0",
 "Outlaw|All I Know": "5FgVVsfimQM",
 "TG|Me And This Crazy Life Of Mine": "B9qZz-m6BL4",
 "K.G.|Intenze": "l2pJLUpczWE",
 "Hung Jury|Gathering Evidence": "hq2RVbDU5qo",
 "Dice|Double Life": "aIx6-CRydfo",
 "Misc?|In My City": "M0sAYZMvlvw",
 "UntouchAbles|Played By Hand": "gK8bQBWN-lw"
};
